name: Auto Sign-in

on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间0点执行

jobs:
  sign_in:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run sign-in script
      run: echo "这里是签到脚本的执行命令"
